Repository traefik/traefik-helm-chart, pull requests merged in 2020-10, with the labels that each got.

#270 Allow to specify custom labels on Service
  traefik/Chart.yaml
  traefik/templates/service.yaml
  traefik/tests/service-config_test.yaml
  traefik/values.yaml
Labels: kind/enhancement, status/2-needs-review, status/3-needs-merge

#275 Fix broken chart icon url
  Makefile
  traefik/Chart.yaml
Labels: status/3-needs-merge

#277 Add Artifact Hub repository metadata file
  Makefile
  artifacthub-repo.yml
  traefik/Chart.yaml
Labels: kind/enhancement, status/3-needs-merge

#278 Update traefik to v2.3.1
  traefik/Chart.yaml
  traefik/tests/container-config_test.yaml
  traefik/values.yaml
Labels: status/3-needs-merge

#273 Create PodSecurityPolicy and RBAC when needed.
  traefik/Chart.yaml
  traefik/templates/rbac/clusterrole.yaml
  traefik/templates/rbac/podsecuritypolicy.yaml
  traefik/templates/rbac/role.yaml
  traefik/tests/podsecuritypolicy-config_test.yaml
  traefik/values.yaml
Labels: kind/enhancement, status/3-needs-merge

#196 Template custom volume name
  traefik/Chart.yaml
  traefik/templates/deployment.yaml
  traefik/tests/container-config_test.yaml
  traefik/values.yaml
Labels: kind/enhancement, status/3-needs-merge

#284 Replace extensions with policy because of deprecation
  traefik/Chart.yaml
  traefik/templates/rbac/clusterrole.yaml
Labels: kind/bug/fix, status/3-needs-merge

#259 Add additional volumes for init and additional containers
  traefik/Chart.yaml
  traefik/templates/deployment.yaml
  traefik/tests/deployment-config_test.yaml
  traefik/values.yaml
Labels: kind/enhancement, status/3-needs-merge

#283 Add a configuration option for an emptyDir as plugin storage
  traefik/Chart.yaml
  traefik/templates/deployment.yaml
  traefik/tests/traefik-config_test.yaml
  traefik/values.yaml
Labels: kind/enhancement, status/3-needs-merge

#285 feat: Enable entrypoint tls config + TLSOption
  traefik/Chart.yaml
  traefik/templates/deployment.yaml
  traefik/templates/tlsoption.yaml
  traefik/tests/traefik-config_test.yaml
  traefik/values.yaml
Labels: kind/enhancement, status/3-needs-merge

#281 fix semver compare
  traefik/Chart.yaml
  traefik/templates/deployment.yaml
  traefik/templates/ingressclass.yaml
  traefik/values.yaml
Labels: kind/bug/fix, status/3-needs-merge

#288 Add chart repo to source
  traefik/Chart.yaml
Labels: kind/enhancement, status/3-needs-merge

#294 Add imagePullSecrets
  traefik/Chart.yaml
  traefik/templates/deployment.yaml
  traefik/tests/deployment-config_test.yaml
  traefik/values.yaml
Labels: kind/enhancement, status/3-needs-merge
