Repository traefik/traefik-helm-chart, pull requests merged in 2020-08, with the labels that each got.

#227 Bump Traefik to 2.2.8
  traefik/Chart.yaml
  traefik/tests/container-config_test.yaml
  traefik/values.yaml
Labels: status/3-needs-merge

#229 Add hostIp to port configuration
  traefik/Chart.yaml
  traefik/templates/deployment.yaml
  traefik/values.yaml
Labels: contributor/waiting-for-corrections, status/3-needs-merge

#225 Add dns policy option
  traefik/Chart.yaml
  traefik/templates/deployment.yaml
  traefik/values.yaml
Labels: enhancement, status/3-needs-merge

#201 Add image pull policy
  traefik/Chart.yaml
  traefik/templates/deployment.yaml
  traefik/tests/deployment-config_test.yaml
  traefik/values.yaml
Labels: enhancement, status/3-needs-merge

#224 Add logging, and http redirect config
  traefik/Chart.yaml
  traefik/templates/deployment.yaml
  traefik/values.yaml
Labels: enhancement, status/3-needs-merge

#240 Dont redirect to websecure by default
  traefik/Chart.yaml
  traefik/values.yaml
Labels: bug/fix, status/3-needs-merge

#241 Fix log level configuration
  traefik/Chart.yaml
  traefik/templates/deployment.yaml
Labels: bug/fix, status/3-needs-merge

#218 PublishedService option
  traefik/Chart.yaml
  traefik/templates/_helpers.tpl
  traefik/templates/deployment.yaml
  traefik/tests/traefik-config_test.yaml
  traefik/values.yaml
Labels: contributor/waiting-for-corrections, enhancement, status/3-needs-merge
