Repository traefik/traefik-helm-chart, pull requests merged in 2020-12, with the labels that each got.

#318 Adding urls that the dashboard will be accessible via to the readme
  README.md
Labels: area/documentation, contributor/waiting-for-corrections, kind/enhancement, status/3-needs-merge

#327 Resolve #303, change CRD version from v1beta1 to v1
  traefik/Chart.yaml
  traefik/crds/ingressroute.yaml
  traefik/crds/ingressroutetcp.yaml
  traefik/crds/ingressrouteudp.yaml
  traefik/crds/middlewares.yaml
  traefik/crds/tlsoptions.yaml
  traefik/crds/tlsstores.yaml
  traefik/crds/traefikservices.yaml
Labels: kind/bug/fix, status/3-needs-merge

#328 Bump Traefik to 2.3.6
  traefik/Chart.yaml
  traefik/tests/container-config_test.yaml
Labels: kind/enhancement, status/3-needs-merge

#332 Revert API Upgrade
  traefik/Chart.yaml
  traefik/crds/ingressroute.yaml
  traefik/crds/ingressroutetcp.yaml
  traefik/crds/ingressrouteudp.yaml
  traefik/crds/middlewares.yaml
  traefik/crds/tlsoptions.yaml
  traefik/crds/tlsstores.yaml
  traefik/crds/traefikservices.yaml
Labels: kind/bug/fix, status/3-needs-merge
