Repository traefik/traefik-helm-chart, pull requests merged in 2020-04, with the labels that each got.

#137 Add support for helm 2
  traefik/Chart.yaml
Labels: enhancement, status/3-needs-merge

#135 add annotations to ingressRoute
  traefik/Chart.yaml
  traefik/templates/dashboard-hook-ingressroute.yaml
  traefik/values.yaml
Labels: enhancement, status/3-needs-merge

#142 follow helm best practices
  traefik/Chart.yaml
  traefik/templates/dashboard-hook-ingressroute.yaml
  traefik/templates/deployment.yaml
  traefik/templates/hpa.yaml
  traefik/templates/pvc.yaml
  traefik/templates/rbac/clusterrole.yaml
  traefik/templates/rbac/clusterrolebinding.yaml
  traefik/templates/rbac/serviceaccount.yaml
  traefik/templates/service.yaml
  traefik/tests/deployment-config_test.yaml
  traefik/values.yaml
Labels: enhancement, status/3-needs-merge

#151 rbac does not need "pods" per documentation
  traefik/Chart.yaml
  traefik/templates/rbac/clusterrole.yaml
Labels: enhancement, status/3-needs-merge

#148 Ability to add custom labels to dashboard's IngressRoute
  traefik/Chart.yaml
  traefik/templates/dashboard-hook-ingressroute.yaml
  traefik/values.yaml
Labels: enhancement, status/3-needs-merge

#147 Add Support for subPath in data volumeMount
  traefik/Chart.yaml
  traefik/templates/deployment.yaml
  traefik/tests/container-config_test.yaml
  traefik/values.yaml
Labels: bot/need-human-merge, enhancement, status/3-needs-merge

#154 Possibility to bind environment variables via envFrom
  traefik/Chart.yaml
  traefik/templates/deployment.yaml
  traefik/tests/deployment-config_test.yaml
  traefik/values.yaml
Labels: enhancement, status/3-needs-merge

#155 Add priorityClassName & securityContext
  traefik/Chart.yaml
  traefik/templates/deployment.yaml
  traefik/tests/deployment-config_test.yaml
  traefik/values.yaml
Labels: enhancement, status/3-needs-merge

#159 clarify project philosophy and guidelines
  .gitignore
  CONTRIBUTING.md
  README.md
  traefik/Chart.yaml
  traefik/README.md
Labels: documentation, status/3-needs-merge

#162 Fix contributing link
  README.md
Labels: enhancement, status/2-needs-review

#161 Remove invalid flags.
  traefik/Chart.yaml
  traefik/values.yaml
Labels: bug, documentation, status/3-needs-merge

#169 Clarify additionnal arguments log
  traefik/Chart.yaml
  traefik/values.yaml
Labels: enhancement, status/3-needs-merge

#171 Update Traefik to v2.2.1
  traefik/Chart.yaml
  traefik/tests/container-config_test.yaml
  traefik/values.yaml
Labels: enhancement, status/3-needs-merge
