Repository traefik/traefik-helm-chart, pull requests merged in 2020-01, with the labels that each got.

#52 Fixed loadBalancerIP spec into values.yaml
  Chart.yaml
  values.yaml
Labels: bug

#51 Disable dashboard ingressRoute by default
  Chart.yaml
  values.yaml
Labels: enhancement

#57 allow affinity settings
  Chart.yaml
  templates/deployment.yaml
  values.yaml
Labels: enhancement

#59 Switch Chart linting to ct
  .travis.yml
  CONTRIBUTING.md
  Guidelines.md
  Makefile
  README.md
  test/README.md
  test/chart_schema.yaml
  test/ct.yaml
  test/lintconf.yaml
  traefik/Chart.yaml
  traefik/templates/_helpers.tpl
  traefik/templates/crd/ingressroute.yaml
  traefik/templates/crd/ingressroutetcp.yaml
  traefik/templates/crd/middlewares.yaml
  traefik/templates/crd/tlsoptions.yaml
  traefik/templates/crd/traefikservice.yaml
  traefik/templates/dashboard-hook-ingressroute.yaml
  traefik/templates/deployment.yaml
  traefik/templates/rbac/clusterrole.yaml
  traefik/templates/rbac/clusterrolebinding.yaml
  traefik/templates/rbac/serviceaccount.yaml
  traefik/templates/service.yaml
  traefik/values.yaml
Labels: enhancement

#67 Make NodePort configurable
  traefik/Chart.yaml
  traefik/templates/service.yaml
  traefik/values.yaml
Labels: enhancement

#70 docs: Fix broken link to Helm Chart Guidelines
  CONTRIBUTING.md
Labels: bug, documentation

#71 Enable configuration of environment variables in traefik deployment
  traefik/Chart.yaml
  traefik/templates/deployment.yaml
  traefik/values.yaml
Labels: enhancement
