Repository traefik/traefik-helm-chart, pull requests merged in 2020-03, with the labels that each got.

#94 Migrate to helm v3
  .travis.yml
  Makefile
  README.md
  traefik/Chart.yaml
  traefik/crds/ingressroute.yaml
  traefik/crds/ingressroutetcp.yaml
  traefik/crds/middlewares.yaml
  traefik/crds/tlsoptions.yaml
  traefik/crds/traefikservices.yaml
  traefik/tests/default-install_test.yaml
Labels: enhancement

#83 Add podAnnotations to the deployment
  traefik/Chart.yaml
  traefik/templates/deployment.yaml
  traefik/values.yaml
Labels: enhancement

#84 Add values to mount secrets or configmaps as volumes to the traefik pod
  traefik/Chart.yaml
  traefik/templates/deployment.yaml
  traefik/values.yaml
Labels: enhancement

#86 Added persistent volume support.
  traefik/Chart.yaml
  traefik/templates/deployment.yaml
  traefik/templates/pvc.yaml
  traefik/values.yaml
Labels: enhancement

#98 Add annotations for PVC
  traefik/Chart.yaml
  traefik/templates/pvc.yaml
  traefik/values.yaml
Labels: enhancement

#100 Expose dashboard by default but only on traefik entrypoint
  traefik/Chart.yaml
  traefik/templates/dashboard-hook-ingressroute.yaml
  traefik/templates/deployment.yaml
  traefik/tests/dashboard-config_test.yaml
  traefik/values.yaml
Labels: enhancement, status/3-needs-merge

#50 Enhance security by add loadBalancerSourceRanges to lockdown ip address.
  traefik/Chart.yaml
  traefik/templates/service.yaml
  traefik/tests/service-config_test.yaml
  traefik/values.yaml
Labels: enhancement, status/3-needs-merge

#101 Add secret as env var
  traefik/Chart.yaml
  traefik/templates/deployment.yaml
  traefik/values.yaml
Labels: enhancement, status/3-needs-merge

#103 Fix volume mount
  traefik/Chart.yaml
  traefik/templates/deployment.yaml
Labels: enhancement, status/3-needs-merge

#97 Not authorise acme if replica > 1
  traefik/Chart.yaml
  traefik/templates/deployment.yaml
Labels: enhancement, status/3-needs-merge

#104 Production ready
  README.md
  traefik/Chart.yaml
  traefik/OWNERS
  traefik/README.md
Labels: enhancement, status/3-needs-merge

#105 Fixed typo in README
  README.md
  traefik/Chart.yaml
  traefik/README.md
Labels: bug, documentation, status/3-needs-merge

#107 Fix replica check
  traefik/Chart.yaml
  traefik/templates/deployment.yaml
  traefik/values.yaml
Labels: bug, status/3-needs-merge

#108 Add support for hostport
  traefik/Chart.yaml
  traefik/templates/deployment.yaml
  traefik/tests/ports-config_test.yaml
  traefik/values.yaml
Labels: enhancement, status/3-needs-merge

#49 expose hostnetwork option
  traefik/Chart.yaml
  traefik/templates/deployment.yaml
  traefik/values.yaml
Labels: enhancement, status/3-needs-merge

#110 Add field enabled for resources
  traefik/Chart.yaml
  traefik/templates/dashboard-hook-ingressroute.yaml
  traefik/templates/deployment.yaml
  traefik/templates/rbac/clusterrolebinding.yaml
  traefik/templates/service.yaml
  traefik/tests/ports-config_test.yaml
  traefik/tests/service-config_test.yaml
  traefik/tests/traefik-config_test.yaml
  traefik/values.yaml
Labels: enhancement, status/3-needs-merge

#111 Cleanup
  traefik/Chart.yaml
  traefik/templates/deployment.yaml
  traefik/tests/traefik-config_test.yaml
  traefik/values.yaml
Labels: enhancement, status/3-needs-merge

#117 Change default values of arrays from objects to actual arrays
  traefik/Chart.yaml
  traefik/values.yaml
Labels: bug, status/3-needs-merge

#120 Correct storage class key name
  traefik/Chart.yaml
  traefik/templates/pvc.yaml
Labels: bug, status/3-needs-merge

#116 Add ability to add annotations to deployment
  traefik/Chart.yaml
  traefik/templates/deployment.yaml
  traefik/values.yaml
Labels: enhancement, status/3-needs-merge

#122 Upgrade traefik version
  traefik/Chart.yaml
  traefik/tests/container-config_test.yaml
  traefik/values.yaml
Labels: enhancement, status/2-needs-review

#123 Upgrade traefik version
  traefik/Chart.yaml
  traefik/tests/container-config_test.yaml
  traefik/values.yaml
Labels: enhancement, status/3-needs-merge

#96 Update to v2.2
  .travis.yml
  Makefile
  traefik/Chart.yaml
  traefik/crds/ingressrouteudp.yaml
  traefik/crds/tlsstores.yaml
  traefik/templates/rbac/clusterrole.yaml
  traefik/tests/container-config_test.yaml
  traefik/values.yaml
Labels: enhancement, status/3-needs-merge

#126 hpa
  traefik/Chart.yaml
  traefik/templates/deployment.yaml
  traefik/templates/hpa.yaml
  traefik/values.yaml
Labels: enhancement, status/3-needs-merge

#129 Add ability to set serviceAccount annotations
  traefik/Chart.yaml
  traefik/templates/rbac/serviceaccount.yaml
  traefik/values.yaml
Labels: enhancement, status/3-needs-merge

#130 Remove secretsEnv value key
  traefik/Chart.yaml
  traefik/templates/deployment.yaml
  traefik/values.yaml
Labels: enhancement, status/3-needs-merge

#132 Add support for externalIPs
  traefik/Chart.yaml
  traefik/templates/service.yaml
  traefik/tests/pod-config_test.yaml
  traefik/tests/ports-config_test.yaml
  traefik/tests/service-config_test.yaml
  traefik/values.yaml
Labels: enhancement, status/3-needs-merge
