Repository traefik/traefik-helm-chart, pull requests merged in 2020-09, with the labels that each got.

#253 Update reference to using kubectl proxy to kubectl port-forward
  traefik/Chart.yaml
  traefik/values.yaml
Labels: enhancement, status/3-needs-merge

#261 chore: move to new organization.
  LICENSE
  Makefile
  README.md
  traefik/Chart.yaml
  traefik/LICENSE
  traefik/README.md
  traefik/tests/container-config_test.yaml
  traefik/tests/deployment-config_test.yaml
  traefik/values.yaml
Labels: enhancement, status/3-needs-merge

#263 Add new helm url
  README.md
  traefik/Chart.yaml
  traefik/README.md
Labels: enhancement, status/3-needs-merge

#267 Release Traefik 2.3
  traefik/Chart.yaml
  traefik/templates/deployment.yaml
  traefik/templates/ingressclass.yaml
  traefik/templates/rbac/clusterrole.yaml
  traefik/tests/container-config_test.yaml
  traefik/values.yaml
Labels: kind/enhancement, status/3-needs-merge

#269 Makefile: spelling error
  Makefile
Labels: area/documentation, kind/bug/fix, status/3-needs-merge

#274 Fix outdated link
  index.md
Labels: status/3-needs-merge
