Repository traefik/traefik-helm-chart, pull requests merged in 2020-11, with the labels that each got.

#299 fix: multiple ImagePullSecrets
  traefik/Chart.yaml
  traefik/templates/deployment.yaml
  traefik/tests/deployment-config_test.yaml
Labels: kind/bug/fix, status/3-needs-merge

#286 Add additionalVolumeMounts for traefik container
  traefik/Chart.yaml
  traefik/templates/deployment.yaml
  traefik/tests/traefik-config_test.yaml
  traefik/values.yaml
Labels: kind/enhancement, status/2-needs-review, status/3-needs-merge

#289 Add list of watched provider namespaces
  traefik/Chart.yaml
  traefik/templates/_helpers.tpl
  traefik/templates/deployment.yaml
  traefik/tests/traefik-config_test.yaml
  traefik/values.yaml
Labels: kind/enhancement, status/3-needs-merge

#300 Specify IngressClass resource when checking for cluster capability
  traefik/Chart.yaml
  traefik/templates/ingressclass.yaml
Labels: kind/bug/fix, status/3-needs-merge

#313 Bump Traefik to 2.3.3
  traefik/Chart.yaml
  traefik/tests/container-config_test.yaml
Labels: kind/enhancement, status/3-needs-merge

#306 add podLabels - custom labels
  traefik/Chart.yaml
  traefik/templates/deployment.yaml
  traefik/tests/deployment-config_test.yaml
  traefik/values.yaml
Labels: kind/enhancement, status/3-needs-merge
