Repository traefik/traefik-helm-chart, pull requests merged in 2020-06, with the labels that each got.

#192 Add pod disruption budget
  traefik/Chart.yaml
  traefik/templates/poddisruptionbudget.yaml
  traefik/values.yaml
Labels: enhancement

#195 Fix PDB with minAvailable set
  traefik/Chart.yaml
  traefik/tests/poddisruptionbudget-config_test.yaml
  traefik/values.yaml
Labels: bug, status/3-needs-merge

#145 UDP support
  traefik/Chart.yaml
  traefik/templates/deployment.yaml
  traefik/templates/service.yaml
  traefik/tests/default-install_test.yaml
  traefik/tests/ports-config_test.yaml
  traefik/tests/service-config_test.yaml
  traefik/values.yaml
Labels: enhancement, status/3-needs-merge

#199 Add existing PVC support(#158)
  traefik/Chart.yaml
  traefik/templates/deployment.yaml
  traefik/templates/pvc.yaml
  traefik/tests/deployment-config_test.yaml
  traefik/values.yaml
Labels: enhancement, status/3-needs-merge

#193 Fix read-only /tmp
  traefik/Chart.yaml
  traefik/templates/deployment.yaml
Labels: enhancement, status/3-needs-merge

#191 Add option to disable providers
  traefik/Chart.yaml
  traefik/templates/deployment.yaml
  traefik/values.yaml
Labels: enhancement, status/3-needs-merge

#214 Update image
  traefik/Chart.yaml
Labels: bug/fix, status/3-needs-merge
