Repository traefik/traefik-helm-chart, pull requests merged in 2021-07, with the labels that each got.

#437 Fix markdownlint issues in README.md
  README.md
Labels: area/documentation, kind/enhancement, status/2-needs-review, status/3-needs-merge

#439 Add support for apiextensions v1 CRDs
  traefik/Chart.yaml
  traefik/crds/ingressroute.yaml
  traefik/crds/ingressroutetcp.yaml
  traefik/crds/ingressrouteudp.yaml
  traefik/crds/middlewares.yaml
  traefik/crds/serverstransports.yaml
  traefik/crds/tlsoptions.yaml
  traefik/crds/tlsstores.yaml
  traefik/crds/traefikservices.yaml
Labels: kind/enhancement, status/3-needs-merge

#442 Revert CRD templating
  traefik/Chart.yaml
  traefik/crds/ingressroute.yaml
  traefik/crds/ingressroutetcp.yaml
  traefik/crds/ingressrouteudp.yaml
  traefik/crds/middlewares.yaml
  traefik/crds/serverstransports.yaml
  traefik/crds/tlsoptions.yaml
  traefik/crds/tlsstores.yaml
  traefik/crds/traefikservices.yaml
Labels: kind/bug/fix, status/3-needs-merge

#444 Add issue and PR templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: area/documentation, kind/enhancement, status/3-needs-merge

#451 Add RBAC for middlewaretcps
  traefik/Chart.yaml
  traefik/templates/rbac/clusterrole.yaml
  traefik/templates/rbac/role.yaml
Labels: kind/bug/fix, status/3-needs-merge

#447 feat(gateway): introduces param / pick Namespace installing Gateway
  traefik/Chart.yaml
  traefik/templates/gateway.yaml
  traefik/tests/gateway-config_test.yaml
  traefik/values.yaml
Labels: kind/enhancement, status/3-needs-merge

#452 Add metrics framework, and prom annotations
  traefik/Chart.yaml
  traefik/templates/_podtemplate.tpl
  traefik/templates/daemonset.yaml
  traefik/templates/deployment.yaml
  traefik/tests/daemonset-config_test.yaml
  traefik/tests/deployment-config_test.yaml
  traefik/values.yaml
Labels: kind/enhancement, status/3-needs-merge

#456 Fixing Prometheus.io/port annotation
  traefik/Chart.yaml
  traefik/templates/daemonset.yaml
  traefik/templates/deployment.yaml
  traefik/tests/daemonset-config_test.yaml
  traefik/tests/deployment-config_test.yaml
Labels: kind/bug/fix, status/3-needs-merge
