Repository traefik/traefik-helm-chart, pull requests merged in 2021-04, with the labels that each got.

#402 Fix pilot dashboard deactivation
  traefik/Chart.yaml
  traefik/templates/_podtemplate.tpl
  traefik/tests/pod-config_test.yaml
Labels: kind/bug/fix, status/3-needs-merge

#406 Fix: ignore provider namespace args on disabled
  traefik/Chart.yaml
  traefik/templates/_podtemplate.tpl
  traefik/tests/traefik-config_test.yaml
Labels: kind/bug/fix, status/2-needs-review, status/3-needs-merge

#407 Fix IngressClass api version
  traefik/Chart.yaml
  traefik/templates/ingressclass.yaml
  traefik/values.yaml
Labels: kind/enhancement, status/3-needs-merge
