Repository traefik/traefik-helm-chart, pull requests merged in 2022-10, with the labels that each got.

#518 Update default HPA API Version to `v2` and add support for behavior
  traefik/Chart.yaml
  traefik/templates/hpa.yaml
  traefik/tests/hpa-config_test.yaml
  traefik/tests/values/hpa.yaml
  traefik/values.yaml
Labels: kind/enhancement

#653 :bug: Ignore kustomization file used for CRDs upgrade
  traefik/.helmignore
  traefik/Chart.yaml
Labels: status/3-needs-merge, kind/bug/confirmed

#557 :lipstick: Affinity templating and example
  traefik/Chart.yaml
  traefik/templates/_podtemplate.tpl
  traefik/tests/deployment-config_test.yaml
  traefik/tests/values/antiaffinity.yaml
  traefik/values.yaml
Labels: kind/bug/fix

#661 :memo: Add Changelog
  Makefile
  README.md
  traefik/Changelog.md
  traefik/Chart.yaml
Labels: area/documentation

#657 :rocket: Enable TLS by default on `websecure` port
  traefik/Changelog.md
  traefik/Chart.yaml
  traefik/tests/traefik-config_test.yaml
  traefik/values.yaml
Labels: kind/enhancement

#663 :sparkles: add optional topologySpreadConstraints
  traefik/Changelog.md
  traefik/Chart.yaml
  traefik/templates/_podtemplate.tpl
  traefik/tests/container-config_test.yaml
  traefik/values.yaml
Labels: kind/enhancement, status/2-needs-review

#667 :goal_net: Fail gracefully when http3 is not enabled correctly
  traefik/Changelog.md
  traefik/Chart.yaml
  traefik/templates/service.yaml
  traefik/tests/pod-config_test.yaml
  traefik/tests/service-config_test.yaml
Labels: kind/bug/fix

#666 :bug: Allow to watch on specific namespaces without using rbac.namespaced
  traefik/Changelog.md
  traefik/Chart.yaml
  traefik/templates/_podtemplate.tpl
  traefik/tests/traefik-config_test.yaml
  traefik/values.yaml
Labels: kind/bug/fix

#674 :art: Improve `IngressRoute` structure
  traefik/Changelog.md
  traefik/Chart.yaml
  traefik/templates/dashboard-hook-ingressroute.yaml
  traefik/tests/dashboard-hook-ingressroute_test.yaml
Labels: kind/bug/fix

#665 :fire: Remove `Pilot` and `fallbackApiVersion`
  traefik/Changelog.md
  traefik/Chart.yaml
  traefik/templates/_podtemplate.tpl
  traefik/templates/ingressclass.yaml
  traefik/tests/pod-config_test.yaml
  traefik/values.yaml
Labels: kind/enhancement, breaking

#425 ✨ add optional ServiceMonitor & PrometheusRule CRDs
  traefik/Changelog.md
  traefik/Chart.yaml
  traefik/templates/prometheusrules.yaml
  traefik/templates/servicemonitor.yaml
  traefik/tests/prometheusrules-config_test.yaml
  traefik/tests/servicemonitor-config_test.yaml
  traefik/tests/values/prometheusrules.yaml
  traefik/tests/values/servicemonitor.yaml
  traefik/values.yaml
Labels: kind/enhancement, contributor/waiting-for-feedback, status/2-needs-review

#677 Remove unused file
  15.2.0.yaml
Labels: kind/bug/fix

#673 Add forwardedHeaders and proxyProtocol config
  traefik/Changelog.md
  traefik/Chart.yaml
  traefik/templates/_podtemplate.tpl
  traefik/tests/traefik-config_test.yaml
  traefik/values.yaml
Labels: kind/enhancement

#662 :bug: Fix `ClusterRole`, `ClusterRoleBinding` names and `app.kubernetes.io/instance` label
  traefik/Changelog.md
  traefik/Chart.yaml
  traefik/templates/_helpers.tpl
  traefik/templates/rbac/clusterrole.yaml
  traefik/templates/rbac/clusterrolebinding.yaml
  traefik/tests/default-install_test.yaml
  traefik/tests/rbac-config_test.yaml
Labels: status/2-needs-review, kind/bug/fix

#681 :bug: Unify all labels selector with traefik chart labels
  traefik/Changelog.md
  traefik/Chart.yaml
  traefik/templates/_helpers.tpl
  traefik/templates/_service.tpl
  traefik/templates/daemonset.yaml
  traefik/templates/deployment.yaml
  traefik/templates/poddisruptionbudget.yaml
  traefik/templates/servicemonitor.yaml
  traefik/tests/values/antiaffinity.yaml
  traefik/values.yaml
Labels: kind/bug/fix

#656 Merge TCP and UDP ports into a single service
  README.md
  traefik/Changelog.md
  traefik/Chart.yaml
  traefik/templates/_podtemplate.tpl
  traefik/templates/_service.tpl
  traefik/templates/service.yaml
  traefik/tests/pod-config_test.yaml
  traefik/tests/ports-config_test.yaml
  traefik/tests/service-config-multiple_test.yaml
  traefik/tests/service-config_test.yaml
  traefik/values.yaml
Labels: kind/enhancement, contributor/waiting-for-feedback, status/2-needs-review

#676 🚀 Add native support for Traefik Hub
  traefik/Changelog.md
  traefik/Chart.yaml
  traefik/templates/NOTES.txt
  traefik/templates/_podtemplate.tpl
  traefik/templates/service-hub.yaml
  traefik/tests/hub-integration-config_test.yaml
  traefik/tests/ingressclass-config_test.yaml
  traefik/values.yaml
Labels: kind/enhancement

#696 ⬆️ Update Traefik appVersion to 2.9.4
  traefik/Changelog.md
  traefik/Chart.yaml
  traefik/tests/container-config_test.yaml
Labels: kind/enhancement
