Repository traefik/traefik-helm-chart, pull requests merged in 2022-01, with the labels that each got.

#552 Update Traefik to v2.6
  traefik/Chart.yaml
  traefik/templates/gateway.yaml
  traefik/templates/gatewayclass.yaml
  traefik/templates/rbac/clusterrole.yaml
  traefik/tests/container-config_test.yaml
  traefik/tests/gateway-config_test.yaml
  traefik/tests/gatewayclass-config_test.yaml
  traefik/values.yaml
Labels: kind/enhancement, status/3-needs-merge

#548 Add setting to enable Instana tracing
  traefik/Chart.yaml
  traefik/templates/_podtemplate.tpl
  traefik/tests/pod-config_test.yaml
  traefik/values.yaml
Labels: kind/enhancement, status/3-needs-merge

#539 Fix anti-affinity example
  traefik/Chart.yaml
  traefik/values.yaml
Labels: area/documentation, status/3-needs-merge, kind/bug/fix

#408 Add shareProcessNamespace option to podtemplate
  traefik/Chart.yaml
  traefik/templates/_podtemplate.tpl
  traefik/tests/pod-config_test.yaml
  traefik/values.yaml
Labels: kind/enhancement
