Repository traefik/traefik-helm-chart, pull requests merged in 2022-11, with the labels that each got.

#693 ✨ Provides Default IngressClass for Traefik by default
  traefik/Changelog.md
  traefik/Chart.yaml
  traefik/templates/ingressclass.yaml
  traefik/tests/default-install_test.yaml
  traefik/tests/ingressclass-config_test.yaml
  traefik/tests/podsecuritypolicy-config_test.yaml
  traefik/tests/rbac-config_test.yaml
  traefik/values.yaml
Labels: kind/enhancement

#699 🐛 Fix IngressClass install on EKS
  traefik/Changelog.md
  traefik/Chart.yaml
  traefik/templates/_podtemplate.tpl
  traefik/templates/daemonset.yaml
  traefik/templates/ingressclass.yaml
  traefik/tests/ingressclass-config_test.yaml
Labels: kind/bug/fix

#695 💬 Support volume secrets with '.' in name
  traefik/Changelog.md
  traefik/Chart.yaml
  traefik/templates/_podtemplate.tpl
  traefik/tests/pod-config_test.yaml
Labels: kind/bug/fix

#700 🎨 Don't require exposed Ports when enabling Hub
  traefik/Changelog.md
  traefik/Chart.yaml
  traefik/templates/service.yaml
  traefik/tests/hub-integration-config_test.yaml
Labels: kind/bug/fix

#703 🔧 Adds more settings & rename (wrong) scrapeInterval to (valid) interval on ServiceMonitor
  traefik/Changelog.md
  traefik/Chart.yaml
  traefik/templates/servicemonitor.yaml
  traefik/tests/servicemonitor-config_test.yaml
  traefik/tests/values/servicemonitor.yaml
  traefik/values.yaml
Labels: kind/bug/fix

#708 🐛 change chart release charts_dir
  .github/workflows/release.yml
Labels: kind/bug/fix

#709 🐛 change chart release index_dir
  .github/workflows/release.yml
Labels: kind/bug/fix

#716 📝 add examples for simple use cases
  EXAMPLES.md
  README.md
Labels: area/documentation, kind/enhancement

#717 Document recent changes in the README
  README.md
  traefik/values.yaml
Labels: area/documentation

#718 ✨ add support for namespace overrides
  traefik/Changelog.md
  traefik/Chart.yaml
  traefik/templates/_helpers.tpl
  traefik/templates/daemonset.yaml
  traefik/templates/dashboard-hook-ingressroute.yaml
  traefik/templates/deployment.yaml
  traefik/templates/gateway.yaml
  traefik/templates/hpa.yaml
  traefik/templates/ingressclass.yaml
  traefik/templates/poddisruptionbudget.yaml
  traefik/templates/pvc.yaml
  traefik/templates/rbac/role.yaml
  traefik/templates/rbac/rolebinding.yaml
  traefik/templates/service-hub.yaml
  traefik/templates/service-internal.yaml
  traefik/templates/service.yaml
  traefik/templates/tlsoption.yaml
  traefik/templates/tlsstore.yaml
  traefik/tests/daemonset-config_test.yaml
  traefik/tests/deployment-config_test.yaml
  traefik/tests/gateway-config_test.yaml
  traefik/tests/hub-integration-config_test.yaml
  traefik/tests/poddisruptionbudget-config_test.yaml
  traefik/tests/rbac-config_test.yaml
  traefik/tests/service-config_test.yaml
  traefik/tests/service-internal-config_test.yaml
  traefik/tests/tlsstore_test.yaml
  traefik/values.yaml
Labels: kind/enhancement

#722 :memo: Add upgrade notes on v16.x
  README.md
Labels: area/documentation

#723 🙈 do not namespace ingress class
  traefik/Changelog.md
  traefik/Chart.yaml
  traefik/templates/ingressclass.yaml
Labels: status/3-needs-merge, kind/bug/fix

#728 :lipstick: Add release notes to GitHub Releases
  .github/workflows/release.yml
Labels: area/documentation, kind/enhancement

#729 :art: Use forked version of helm-changelog with better formating
  Makefile
Labels: area/documentation, kind/bug/fix

#731 🐛 Fix namespace override which was missing on `ServiceAccount`
  traefik/Changelog.md
  traefik/Chart.yaml
  traefik/templates/rbac/serviceaccount.yaml
  traefik/tests/rbac-config_test.yaml
Labels: kind/bug/fix

#727 Add (optional) dedicated metrics service
  traefik/Changelog.md
  traefik/Chart.yaml
  traefik/templates/_service-metrics.tpl
  traefik/templates/service-metrics.yaml
  traefik/templates/servicemonitor.yaml
  traefik/tests/service-metrics-config_test.yaml
  traefik/tests/servicemonitor-config_test.yaml
  traefik/tests/values/servicemonitor.yaml
  traefik/values.yaml
Labels: kind/enhancement

#721 :sparkles: Provides default static install
  .github/workflows/release.yml
Labels: kind/enhancement

#737 🐛 Fix namespaceSelector on ServiceMonitor
  traefik/Changelog.md
  traefik/Chart.yaml
  traefik/templates/servicemonitor.yaml
Labels: kind/bug/fix

#739 :memo: Move dashboard instructions from README to EXAMPLES
  EXAMPLES.md
  README.md
Labels: area/documentation

#743 🐛 Fix template issue with obsolete helm version + add helm version requirement
  README.md
  traefik/Changelog.md
  traefik/Chart.yaml
  traefik/templates/_podtemplate.tpl
  traefik/templates/deployment.yaml
Labels: kind/bug/fix

#746 :bug: Add missing scheme in help on Traefik Hub integration
  traefik/templates/NOTES.txt
  traefik/tests/notes_test.yaml
Labels: area/documentation

#747 🔍️ Add filePath support on access logs
  traefik/Changelog.md
  traefik/Chart.yaml
  traefik/templates/_podtemplate.tpl
  traefik/tests/traefik-config_test.yaml
  traefik/values.yaml
Labels: kind/enhancement

#748 :adhesive_bandage: Add quotes for artifacthub changelog parsing
  hack/changelog.sh
  traefik/Changelog.md
  traefik/Chart.yaml
Labels: area/documentation, kind/bug/fix
