Repository traefik/traefik-helm-chart, pull requests merged in 2022-09, with the labels that each got.

#628 Update Traefik version to v2.8.4
  traefik/Chart.yaml
  traefik/tests/container-config_test.yaml
Labels: kind/enhancement, status/3-needs-merge

#630 Update Traefik version to v2.8.5
  traefik/Chart.yaml
  traefik/tests/container-config_test.yaml
Labels: kind/enhancement, status/3-needs-merge

#632 Update Traefik to v2.8.7
  traefik/Chart.yaml
  traefik/tests/container-config_test.yaml
Labels: kind/enhancement, status/3-needs-merge

#619 Suggest an alternative port for metrics
  traefik/Chart.yaml
  traefik/values.yaml
Labels: status/3-needs-merge

#601 Add TLSStore resource to chart
  traefik/Chart.yaml
  traefik/templates/tlsstore.yaml
  traefik/values.yaml
Labels: kind/enhancement, status/3-needs-merge

#563 Add ingressclasses to traefik role
  traefik/Chart.yaml
  traefik/templates/rbac/role.yaml
Labels: status/3-needs-merge, kind/bug/fix

#633 :bug: Fix ingressClass support when rbac.namespaced=true (#499)
  traefik/Chart.yaml
  traefik/templates/rbac/clusterrole.yaml
  traefik/templates/rbac/clusterrolebinding.yaml
  traefik/templates/rbac/role.yaml
  traefik/tests/rbac-config_test.yaml
Labels: status/3-needs-merge, kind/bug/confirmed

#636 🐛 fix rbac templating
  traefik/Chart.yaml
  traefik/templates/rbac/clusterrole.yaml
Labels: kind/bug/fix

#586 feat: add create gateway option
  traefik/Chart.yaml
  traefik/templates/gateway.yaml
  traefik/values.yaml
Labels: kind/enhancement, status/3-needs-merge

#637 :memo: Reference values & repo on helm welcome page (Fix #599)
  index.md
Labels: area/documentation, status/3-needs-merge

#627 feat: add lifecycle for prestop and poststart
  traefik/Chart.yaml
  traefik/templates/_podtemplate.tpl
  traefik/tests/daemonset-config_test.yaml
  traefik/tests/deployment-config_test.yaml
  traefik/values.yaml
Labels: kind/enhancement, status/3-needs-merge

#608 Add missing tracing options
  traefik/Chart.yaml
  traefik/templates/_podtemplate.tpl
  traefik/tests/pod-config_test.yaml
  traefik/values.yaml
Labels: kind/enhancement, status/3-needs-merge

#554 Add support HTTPS scheme for healthcheks
  traefik/Chart.yaml
  traefik/templates/_podtemplate.tpl
  traefik/tests/traefik-config_test.yaml
  traefik/values.yaml
Labels: kind/enhancement, status/3-needs-merge

#638 :arrow_up: Upgrade helm, ct & unittest
  .github/workflows/deploy.yml
  .github/workflows/test.yml
  Makefile
  chart_schema.yaml
  ct.yaml
  lint/chart_schema.yaml
  lintconf.yaml
  traefik/Chart.yaml
  traefik/tests/ports-config_test.yaml
Labels: kind/enhancement
