Repository traefik/traefik-helm-chart, pull requests merged in 2023-02, with the labels that each got.

#784 :boom: Rename image.name => image.repository
  traefik/templates/_helpers.tpl
  traefik/tests/container-config_test.yaml
  traefik/values.yaml
Labels: kind/bug/fix, breaking

#785 :bug: Disabling dashboard ingressroute should delete it
  traefik/templates/dashboard-ingressroute.yaml
  traefik/tests/dashboard-ingressroute_test.yaml
Labels: kind/bug/fix, breaking

#786 💥 New release with BREAKING changes
  traefik/Changelog.md
  traefik/Chart.yaml
Labels: kind/enhancement

#792 Added volumeName to PersistentVolumeClaim
  traefik/templates/pvc.yaml
  traefik/tests/pvc-config_test.yaml
  traefik/values.yaml
Labels: kind/enhancement, contributor/waiting-for-corrections
