Repository traefik/traefik-helm-chart, pull requests merged in 2023-03, with the labels that each got.

#801 🚨 Fail when enabling PSP on Kubernetes v1.25+
  traefik/templates/rbac/podsecuritypolicy.yaml
  traefik/tests/podsecuritypolicy-config_test.yaml
Labels: kind/bug/fix

#803 doc: Improve upgrade command
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
Labels: area/documentation

#805 :sparkles: release 21.2.0
  traefik/Changelog.md
  traefik/Chart.yaml
Labels: kind/enhancement
